language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer update -o
  - touch storage/testing.sqlite
  - php artisan migrate --database=sqlite_testing --force
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run api
  - ./vendor/bin/phpunit
